// Auto-generated by avdl-compiler v1.1.0 (https://github.com/keybase/node-avdl-compiler)
//   Input file: avdl/gpg_common.avdl
//   Generated : Tue Mar 01 2016 11:09:12 GMT-0500 (EST)

package keybase1

import (
	rpc "github.com/keybase/go-framed-msgpack-rpc"
)

type GPGKey struct {
	Algorithm  string        `codec:"algorithm" json:"algorithm"`
	KeyID      string        `codec:"keyID" json:"keyID"`
	Creation   string        `codec:"creation" json:"creation"`
	Expiration string        `codec:"expiration" json:"expiration"`
	Identities []PGPIdentity `codec:"identities" json:"identities"`
}

type GpgCommonInterface interface {
}

func GpgCommonProtocol(i GpgCommonInterface) rpc.Protocol {
	return rpc.Protocol{
		Name:    "keybase.1.gpgCommon",
		Methods: map[string]rpc.ServeHandlerDescription{},
	}
}

type GpgCommonClient struct {
	Cli rpc.GenericClient
}
